### ISSUE TITLE
New location of mps-youtube

### ISSUE THREAD

**Issue by evolutionxbox** [np1/Fuck-Microsoft#1]
Where did you move it to?

**Comment by ritiek** [comment]
This really sucks. Luckily, I still have the most up to date fork for both [mps-youtube](https://github.com/ritiek/mps-youtube) and [pafy](https://github.com/ritiek/pafy).

@np1 Thanks a lot for starting these wonderful projects! Is there still someplace where we could continue contributing to them?  Even though, it would be never be quite the same but there really are many people who wouldn't want these projects to just die yet.

**Comment by ids1024** [comment]
I just noticed @np1 deleted the repos...

GitLab, perhaps? I also like the look of Gitea for something self-hosted, but that's not really ideal until they figure out a system for federation (go-gitea/gitea#1612), and would require hosting.

**Comment by ids1024** [comment]
Repositories restored; see mps-youtube/mps-youtube#841.
